stages:
  - build

variables:
  IMAGE_NAME: $DOCKERHUB_USERNAME/api-ingestion:latest

build_docker:
  stage: build
  tags:
    - dind
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  only:
    - main
    - ci/docker-build-deploy

  script:
    # Vérification des variables nécessaires
    - |
      if [ -z "$DOCKERHUB_USERNAME" ]; then
        echo "❌ DOCKERHUB_USERNAME is not set"
        exit 1
      fi
      if [ -z "$DOCKERHUB_TOKEN" ]; then
        echo "❌ DOCKERHUB_TOKEN is not set"
        exit 1
      fi

    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - docker build -t $IMAGE_NAME -f ./Dockerfile .
    - docker push $IMAGE_NAME
