apiVersion: v1
kind: ConfigMap
metadata:
  name: api-capteur-config
data:
  DB_HOST: "postgis"
  DB_PORT: "5432"
  DB_USERNAME: "prod_user"
  DB_DATABASE: "projet_simon_prod"
  PORT: "3000"
  NODE_ENV: "production"
