apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-client-config
data:
  NODE_ENV: "production"
  DB_HOST: "postgis"
  DB_PORT: "5432"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  DB_DATABASE: "projet_simon"
  PORT: "3003"
